//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mShop
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mshopEntities : DbContext
    {
        public mshopEntities()
            : base(GetConnectionString())
        {
        }

        public mshopEntities(string username, string password)
           : base(GetConnectionString(username, password))
        { }

        public void SetCommandTimeOut(int Timeout)
        {
            var objectContext = (this as IObjectContextAdapter).ObjectContext;
            objectContext.CommandTimeout = Timeout;
        }

        public static string GetConnectionString()
        {
            return @"metadata = res://*/MShopEntityModel.csdl|res://*/MShopEntityModel.ssdl|res://*/MShopEntityModel.msl;provider=MySql.Data.MySqlClient;provider connection string=';server=localhost;user id=root;database=MShop'";
        }

        public static string GetConnectionString(string username, string password)
        {
            return @"metadata = res://*/MShopEntityModel.csdl|res://*/MShopEntityModel.ssdl|res://*/MShopEntityModel.msl;provider=MySql.Data.MySqlClient;provider connection string=';server=localhost;user id=" + username + ";password=" + password + ";database=MShop'";
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Products> Products { get; set; }
        public DbSet<Shops> Shops { get; set; }
        public DbSet<Users> Users { get; set; }
        public DbSet<Warehouses> Warehouses { get; set; }
        public DbSet<Products_Shops> Products_Shops { get; set; }
        public DbSet<Products_Warehouses> Products_Warehouses { get; set; }
        public DbSet<products_in_shop> products_in_shop { get; set; }
        public DbSet<products_in_warehouse> products_in_warehouse { get; set; }
    }
}
