//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mShop
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mshopEntities : DbContext
    {
        public mshopEntities()
            : base("name=mshopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Products> Products { get; set; }
        public DbSet<Shops> Shops { get; set; }
        public DbSet<Users> Users { get; set; }
        public DbSet<Warehouses> Warehouses { get; set; }
        public DbSet<Products_Shops> Products_Shops { get; set; }
        public DbSet<Products_Warehouses> Products_Warehouses { get; set; }
    }
}
