//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public Products()
        {
            this.Products_Shops = new HashSet<Products_Shops>();
            this.Products_Warehouses = new HashSet<Products_Warehouses>();
        }
    
        public int P_Id { get; set; }
        public string Name { get; set; }
        public string Brand { get; set; }
        public decimal Price { get; set; }
        public string Category { get; set; }
        public string Barcode { get; set; }
        public byte[] Thumbnail { get; set; }
    
        public virtual ICollection<Products_Shops> Products_Shops { get; set; }
        public virtual ICollection<Products_Warehouses> Products_Warehouses { get; set; }
    }
}
