//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shops
    {
        public Shops()
        {
            this.Products_Shops = new HashSet<Products_Shops>();
            this.Users = new HashSet<Users>();
            this.Warehouses = new HashSet<Warehouses>();
        }
    
        public int S_Id { get; set; }
        public string Name { get; set; }
        public string City { get; set; }
    
        public virtual ICollection<Products_Shops> Products_Shops { get; set; }
        public virtual ICollection<Users> Users { get; set; }
        public virtual ICollection<Warehouses> Warehouses { get; set; }
    }
}
