//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int U_Id { get; set; }
        public string Firstname { get; set; }
        public string Surname { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public Nullable<int> S_Id { get; set; }
        public Nullable<int> W_Id { get; set; }
    
        public virtual Shops Shops { get; set; }
        public virtual Warehouses Warehouses { get; set; }
    }
}
