//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warehouses
    {
        public Warehouses()
        {
            this.Products_Warehouses = new HashSet<Products_Warehouses>();
            this.Users = new HashSet<Users>();
            this.Shops = new HashSet<Shops>();
        }
    
        public int W_Id { get; set; }
        public string Name { get; set; }
        public string City { get; set; }
        public string Category { get; set; }
    
        public virtual ICollection<Products_Warehouses> Products_Warehouses { get; set; }
        public virtual ICollection<Users> Users { get; set; }
        public virtual ICollection<Shops> Shops { get; set; }
    }
}
